# Generated by Django 4.2.26 on 2025-11-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("manufacturer", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("synth", "Synthesizer"),
                            ("drum_machine", "Drum Machine"),
                            ("sampler", "Sampler"),
                            ("groovebox", "Groovebox"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "pdf_path",
                    models.CharField(
                        help_text="Path to PDF file (local or S3 URL)", max_length=500
                    ),
                ),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False,
                        help_text="If True, only premium users can access",
                    ),
                ),
                ("page_count", models.IntegerField(blank=True, null=True)),
                (
                    "pinecone_namespace",
                    models.CharField(
                        blank=True,
                        help_text="Namespace in Pinecone for this manual's vectors",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Manual",
                "verbose_name_plural": "Manuals",
                "db_table": "manuals",
                "ordering": ["-created_at"],
            },
        ),
    ]
